schoolnow/urls.py
from django.conf.urls import url, include
from . import views
from . import views as core_views
from django.contrib.auth import views as auth_views

app_name = 'schoolnow'

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<mensagem_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^bemvindo/$', views.bemvindo, name='bemvindo'),
   
    url(r'^criarmemorando/$', views.criarmemorando, name='criarmemorando'),
    url(r'^memorias/$', views.memorias, name='memorias'),
    #url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.password_reset_confirm, {'template_name': 'password_reset_confirm.html', 'post_change_redirect': 'schoolnow:password_reset_confirm'}, name='password_reset_confirm'),
    #url(r'^reset/$', views.reset, name='reset'),
    #url(r'^songs/$', views.songs, name='songs'),
    #url(r'^reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^reset/$', views.reset, name='reset'),

    #url(r'^accounts/login/$')

        
]

    #url(r'^register/$', core_views.register, name='register'),
    #url(r'^criarmemorado/$', views.update_profile, name='criarmemorado'),

schoolnow/templates/schoolnow/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" type="image/png" href="{%  static 'schoolnow/images/favicon.ico' %}"/>


    
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="{% static 'schoolnow/marketing.css' %}">

             <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

  


</head>
<body>

<div class="header">
    <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'schoolnow:index' %}"><b>SCHOOLNOW</b></a>


        <ul class="pure-menu-list">
   

            <li class="pure-menu-item"><a href="{% url 'schoolnow:memorias' %}" class="pure-menu-link">Memórias</a></li>
            <li class="pure-menu-item"><a href="{% url 'schoolnow:logout_user' %}" class="pure-menu-link"><b>Sair</b></a></li>

            
        </ul>
    </div>
</div>





{% block body %}
{% endblock %}
</body>
</html>

schoolnow/templates/schoolnow/bemvindo.html
{% extends 'schoolnow/base_visitor.html' %}
{% block title %}Bem-vindo!!{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}


      {% load staticfiles %}


<!DOCTYPE html>
<html>
<head>



<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">

<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->
    
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
    <title></title>



<style>

body{
	background-color: white;
}
.content-wrapper{
	position: relative;
	top: 80px;
	background-color: white;
}


.footer{
    text-align: center;
    background-color: black;
    position: relative;
    top: 230px;
    height: 80px;
}

p{
	font-family: 'Bangers', cursive;
	font-size: 60px;
	line-height: 50px;
	color: black;
}
</style>
</head>
<body>





<div class="content-wrapper">
  
   
    <div class="content">

        <div class="pure-g">
            <div class="l-box-lrg pure-u-1 pure-u-md-2-5">
                

                <p>Tudo beleza {{ user }}? deixe sua mensagem e fale do impacto do SCHOOLNOW<br> na sua vida!!</p>

     <a href="{% url 'schoolnow:criarmemorando' %}"> <button class="pure-button pure-button-primary">Deixar uma mensagem!</button></a>


                    
            </div>

            <div class="l-box-lrg pure-u-1 pure-u-md-3-5">
                

                <img src="{% static 'schoolnow/images/IMG-20161016-WA0014.jpg' %}" class="pure-img-responsive">
            </div>
        </div>

    </div>


</div>








<div class="footer"><br>
    Projeto SCHOOLNOW. Todos os direitos reservados

</div>






</body>
</html>














{% endblock %}

schoolnow/templates/schoolnow/create_song.html
{% extends 'music/base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'music:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

schoolnow/templates/schoolnow/criarmemorado.html
{% extends 'schoolnow/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block forums_active %}active{% endblock %}

{% block body %} 


      {% load staticfiles %}









<form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ form.as_p }}
  <button type="submit">Save changes</button>
</form>





{% endblock %}

schoolnow/templates/schoolnow/criarmemorando.html
{% extends 'schoolnow/base_visitor.html' %}
{% block title %}Criar Memorando || SCHOOLNOW{% endblock %}

{% block body %} 


      {% load staticfiles %}



<html>




 <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    

    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
   
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->
   
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">


   
 <link rel="stylesheet" href="{% static 'schoolnow/marketing.css' %}">
     <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">




<head>
    

<style>

body{
    background-color: #C0D5D0;
}
.msg{
    background-color: green;
    height: 100px;
    width: 
}

.pure-g{
 
    width: 100%;
    height: 185px;
    line-height: 70%;
    background-color: white;

    color: black;
    font-family: 'Quicksand', sans-serif;
    padding-right: 30px;
    border-radius: 0px;
        border: 1px solid black;



}

.pure-g p, h4{
        font-family: 'Quicksand', sans-serif;
        position: relative;
        left: 30px;
}




/*
 * -- BASE STYLES --
 * Most of these are inherited from Base, but I want to change a few.
 */
body {
    color: #526066;
}

h2, h3 {
    letter-spacing: 0.25em;
    text-transform: uppercase;
    font-weight: 600;
}

p {
    line-height: 1.6em;
}


/*
 * -- Layout Styles --
 */
.l-content {
    margin: 0 auto;
}

.l-box {
    padding: 0.5em 2em;
}

/*
 * -- MENU STYLES --
 * Make the menu have a very faint box-shadow.
 */
.pure-menu {
    box-shadow: 0 1px 1px rgba(0,0,0, 0.10);
}

.pure-menu-link {
    padding: .5em .7em;
}


/*
 * -- BANNER --
 * The top banner with the headings. By using a combination
 * of `display: table;` and `display: table-cell;`, we can
 * vertically center the text.
 */

.banner {
    background: transparent url('http://24.media.tumblr.com/ccb268832580ac12951828a1c179de69/tumblr_mo2xbk8JUK1st5lhmo1_1280.jpg') 0 0 no-repeat fixed;
    text-align: center;
    background-size: cover;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://24.media.tumblr.com/ccb268832580ac12951828a1c179de69/tumblr_mo2xbk8JUK1st5lhmo1_1280.jpg', sizingMethod='scale');

    height: 200px;
    width: 100%;
    margin-bottom: 3em;
    display: table;
}

    .banner-head {
        display: table-cell;
        vertical-align: middle;
        margin-bottom: 0;
        font-size: 2em;
        color: white;
        font-weight: 500;
        text-shadow: 0 1px 1px black;
    }



/*
 * -- PRICING TABLE WRAPPER --
 * This element wraps up all the pricing table elements
 */
 .pricing-tables,
 .information {
    max-width: 980px;
    margin: 0 auto;
 }
.pricing-tables {
    margin-bottom: 3.125em;
    text-align: center;
}

/*
 * -- PRICING TABLE  --
 * Every pricing table has the .pricing-table class
 */
.pricing-table {
    margin: 0 0.5em 2em;
    padding: 0 0 3em;
}

/*
 * -- PRICING TABLE HEADER COLORS --
 * Choose a different color based on the type of pricing table.
 */
.pricing-table-free .pricing-table-header {
    background: url({% static 'schoolnow/images/samara.jpg' %}); 

}

.pricing-table-biz .pricing-table-header {
        background: url({% static 'schoolnow/images/joao23.jpg' %}); 

}

/*
 * -- PRICING TABLE HEADER --
 * By default, a header is black/white, and has some styles for its <h2> name.
 */
.pricing-table-header {
            background: url({% static 'schoolnow/images/encontro.jpg' %}); 

    color: #fff;
}
    .pricing-table-header h2 {
        margin: 0;
        padding-top: 2em;
        font-size: 1em;
        font-weight: normal;

    }


/*
 * -- PRICING TABLE PRICE --
 * Styles for the price and the corresponding <span>per month</span>
 */
.pricing-table-price {
    font-size: 6em;
    margin: 0.2em 0 0;
    font-weight: 100;
}
    .pricing-table-price span {
        display: block;
        text-transform: uppercase;
        font-size: 0.2em;
        padding-bottom: 2em;
        font-weight: 400;
        color: rgba(255, 255, 255, 0.5);
        *color: #fff;
    }



/*
 * -- PRICING TABLE LIST --
 * Each pricing table has a <ul> which is denoted by the .pricing-table-list class
 */
.pricing-table-list {
    list-style-type: none;
    margin: 0;
    padding: 0;
    text-align: center;
    font-family: 'Gloria Hallelujah', cursive;
    font-size: 20px;

}


/*
 * -- PRICING TABLE LIST ELEMENTS --
 * Styles for the individual list elements within each pricing table
 */
.pricing-table-list li {
    padding: 0.8em 0;
    background: #f7f7f7;
    border-bottom: 1px solid #e7e7e7;
}


/*
 * -- PRICING TABLE BUTTON --
 * Styles for the "Choose" button at the bottom of a pricing table.
 * This inherits from Pure Button.
 */
.button-choose {
    border: 1px solid #ccc;
    background: #fff;
    color: #333;
    border-radius: 2em;
    font-weight: bold;
    position: relative;
    bottom: -1.5em;
}

.information-head {
    color: black;
    font-weight: 500;
}

.footer {
    background: #111;
    color: #888;
    text-align: center;
}
    .footer a {
        color: #ddd;
    }



/*
 * -- TABLET MEDIA QUERIES --
 * On tablets, we want to slightly adjust the size of the banner
 * text and add some vertical space between the various pricing tables
 */
@media(min-width: 767px) {

    .banner-head {
        font-size: 4em;
    }
    .pricing-table {
        margin-bottom: 0;
    }

}

/*
 * -- PHONE MEDIA QUERIES --
 * On phones, we want to reduce the height and font-size of the banner further
 */
@media (min-width: 480px) {
    .banner {
        height: 400px;
    }
    .banner-head {
        font-size: 3em;
    }

    .pure-g p h4{
        position: relative;
        right: 50px;

    }


}



.title{
    font-size: 20px;
    position: relative;
    left: 45px;
    width: 90%;
}


.row-inicial input{
  width: 50px;
  height: 10px;
  border-radius: 5px;
    
}


.footer{
    text-align: center;
    background-color: black;
    position: relative;
    top: 230px;
    height: 80px;
}

input{
    width: 300px;
    height: 200px;
}

button{
    border-radius: 5px;
    color: black;

}

form{
   
    background: url({% static 'schoolnow/images/fotopostagem.png' %}); 
    background-size: cover;
    font-size: 18px;



    
}


</style>


</head>


<body>



<br><br><br><br>



<center>
<form method="post">
  {% csrf_token %}<br>
  
  {{ form.as_p }}
  <button type="submit">Salvar mensagem!</button><br><br>
</form>
</center>


<br><br>







    <p class="title"><b>Algumas mensagens para você se inspirar!! :)</b></p>


{% if memorando_all %}
    
        

        {% for mensagem in memorando_all %}

<div class="pure-g">

<div class="pure-u-1 pure-u-md-1-2">
<p>   {{ mensagem.memorando  }} </p>
<h4>Postado por: {{ mensagem.created_by  }} em {{ mensagem.created_date }}</h4>



       
 </div>

         </div>

         <br>
        {% endfor %}

       


    
{% else %}
    <h3>You dont</h3>
{% endif %}







    





<div class="footer"><br>
    Projeto SCHOOLNOW. Todos os direitos reservados

</div>




</body>

</html>
{% endblock %}

schoolnow/templates/schoolnow/detail.html
{% extends 'schoolnow/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}







<br><br><br><br>

<a href="{% url 'schoolnow:detail' mensagem.id %}">
                        {% if mensagem.memorando %}
                            
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ mensagem.memorando }} <small></small></h1>

                    









{% endblock %}

schoolnow/templates/schoolnow/form_template.html
{% for field in form %}
    
            <span>{{ field.errors }}</span>
      
        <label>{{ field.label_tag }}</label>
        <div>{{ field }}</div>
   
{% endfor %}

schoolnow/templates/schoolnow/index.html
{% extends 'schoolnow/base.html' %}

{% block body %}

       {% load staticfiles %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1">

    <meta name="description" content="A layout example that shows off a responsive product landing page.">
    <title>Landing Page &ndash; Layout Examples &ndash; Pure</title>
    
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->
    
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    
        <!--[if lte IE 8]>
            <link rel="stylesheet" href="css/layouts/marketing-old-ie.css">
        <![endif]-->
        <!--[if gt IE 8]><!-->
            <link rel="stylesheet" href="{% static 'schoolnow/marketing.css' %}">
        <!--<![endif]-->

                     <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">


<style>


body{
             font-family: 'Quicksand', sans-serif;

}

.splash-container {
    background: url({% static 'schoolnow/images/segundob.jpg' %}); 
    background-size: cover;




}


.splash-head{
    font-size: 25px;
    border: 1px solid white;
    color: black;
    border-radius: 7px;
    padding: 1em 1.0em;
    background-color: white;





}
.splash-subhead{
    color: black;
}

.splash-subhead-mid{
    color: white;
}

.home-menu .pure-menu-heading {
    color: white;
    font-weight: 400;
    font-size: 120%;


}


.footer{
    text-align: center;
    background-color: black;
    position: relative;
    top: 215px;
    height: 80px;
}
</style>
</head>
<body>









<div class="splash-container pure-img-responsive">
    <div class="splash">
        <h1 class="splash-head"><b>PROJETO #SCHOOLNOW</b></h1>
        <p class="splash-subhead">
            <b class="splash-subhead-mid">Seja bem-vindo participante!</b>
        </p>
        <p>
            <a href="{% url 'schoolnow:login_user' %}" class="pure-button pure-button-primary">Deixar uma mensagem!! :)</a>
        </p>
    </div>
</div>



<br><br><br>
<br><br><br>

<br><br><br>

<br><br><br>



<div class="footer"><br>
    Projeto SCHOOLNOW. Todos os direitos reservados

</div>



</body>
</html>

















{% endblock %}

schoolnow/templates/schoolnow/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
  <p>
    Senha Alterada.
  </p>
{% endblock %}

schoolnow/templates/schoolnow/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
  {% if validlink %}
    <h3>Mudar Senha</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Mudar senha</button>
    </form>
  {% else %}
    <p>
        O Link que o usuário clicou é inválido
    </p>
  {% endif %}
{% endblock %}

schoolnow/templates/schoolnow/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
  <p>
    Esse template vai ser exibido quando o e-mail for enviado ao usuário
  </p>
{% endblock %}

schoolnow/templates/schoolnow/password_reset_email.html
{% autoescape off %}
Usuário: {{ user.get_username }}

Lorem ipsum dolor sit amet consectetur adipisicing elit. 
Quidem quibusdam, in nam velit asperiores expedita quae harum nesciunt 
voluptatum qui pariatur deleniti? Aperiam maiores, itaque doloremque quam maxime inventore deserunt.

Clique no link:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Lorem ipsum dolor sit amet consectetur adipisicing elit. 
Impedit odio reiciendis debitis sunt, quibusdam aperiam distinctio, 
iure error voluptas explicabo ratione molestiae corrupti facilis nemo alias 
quos aliquam est voluptate.
{% endautoescape %}

schoolnow/templates/schoolnow/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
  <h3>Esqueci a Senha</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
  </form>
{% endblock %}